version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    container_name: user-service

  results-service:
    build: ./results-service
    ports:
      - "3002:3002"
    container_name: results-service

  notifications-service:
    build: ./notifications-service
    ports:
      - "3003:3003"
    container_name: notifications-service

  info-service:
    build: ./info-service
    ports:
      - "3004:3004"
    container_name: info-service

  gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: gateway
