version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3001"
    networks:
      - mpr-network

  results-service:
    build:
      context: ./results-service
    ports:
      - "3002:3002"
    networks:
      - mpr-network

  notifications-service:
    build:
      context: ./notifications-service
    ports:
      - "3003:3003"
    networks:
      - mpr-network

  info-service:
    build:
      context: ./info-service
    ports:
      - "3004:3004"
    networks:
      - mpr-network

  gateway:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - results-service
      - notifications-service
      - info-service
    networks:
      - mpr-network

  frontend-service:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - mpr-network

networks:
  mpr-network:
    driver: bridge
